site_name: My Docs

nav:
    - Home: index.md
    - Code:
        - Extract:
          - Base: code/extract/base.md
          - Deconvolution: code/extract/deconvolution.md
          - Fstack: code/extract/fstack.md
          - Scale: code/extract/scale.md
        - Find Spots:
          - Base: code/find_spots/base.md
        - Call Spots:
          - Base: code/call_spots/base.md
          - Bleed Matrix: code/call_spots/bleed_matrix.md

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings