site_name: My Docs

nav:
    - Home: index.md
    - Code:
        - Extract:
          - Base: code/extract/base.md
          - Deconvolution: code/extract/deconvolution.md
          - Fstack: code/extract/fstack.md
          - Scale: code/extract/scale.md
        - Find Spots:
          - Base: code/find_spots/base.md
        - Point Cloud Registration:
          - Base: code/pcr/base.md
        - Call Spots:
          - Base: code/call_spots/base.md
          - Bleed Matrix: code/call_spots/bleed_matrix.md
        - Pipeline:
            - Run: code/pipeline/run.md
            - Basic Info: code/pipeline/basic_info.md
            - Extract: code/pipeline/extract_run.md
            - Find Spots: code/pipeline/find_spots.md
            - Register Initial: code/pipeline/register_initial.md
            - Register: code/pipeline/register.md
            - Reference Spots: code/pipeline/reference_spots.md
            - Call Reference Spots: code/pipeline/call_reference_spots.md

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings