site_name: My Docs

nav:
    - Home: index.md
    - Code:
        - Extract:
          - Base: code/extract/base.md
          - Deconvolution: code/extract/deconvolution.md
          - Fstack: code/extract/fstack.md
          - Scale: code/extract/scale.md

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings