site_name: My Docs

nav:
    - Home: index.md
    - Code:
        - Setup:
            - Notebook: code/setup/notebook.md
            - Tile Detail: code/setup/tile_details.md
        - Extract:
            - Base: code/extract/base.md
            - Deconvolution: code/extract/deconvolution.md
            - Fstack: code/extract/fstack.md
            - Scale: code/extract/scale.md
        - Find Spots:
            - Base: code/find_spots/base.md
        - Stitch:
            - Shift: code/stitch/shift.md
            - Tile Origin: code/stitch/tile_origin.md
        - Point Cloud Registration:
            - Base: code/pcr/base.md
        - Spot Colors:
            - Base: code/spot_colors/base.md
        - Call Spots:
            - Base: code/call_spots/base.md
            - Bleed Matrix: code/call_spots/bleed_matrix.md
        - Pipeline:
            - Run: code/pipeline/run.md
            - Basic Info: code/pipeline/basic_info.md
            - Extract: code/pipeline/extract_run.md
            - Find Spots: code/pipeline/find_spots.md
            - Stitch: code/pipeline/stitch.md
            - Register Initial: code/pipeline/register_initial.md
            - Register: code/pipeline/register.md
            - Reference Spots: code/pipeline/reference_spots.md
            - Call Reference Spots: code/pipeline/call_reference_spots.md

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings